import org.junit.Test;
import chapter1.Question2;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kevin' at '12/29/17 2:29 PM' with Gradle 3.0
 *
 * @author kevin, @date 12/29/17 2:29 PM
 */
public class Question2Test {
    @Test public void testcheckPermutationReturnsTrue() {
        assertTrue("checkPermutation should return 'true' if unique", Question2.checkPermutation("allo", "llao"));
    }
    @Test public void testcheckPermutationReturnsFalse() {
        assertFalse("checkPermutation should return 'false' if unique", Question2.checkPermutation("ab", "cd"));
    }
}
