import org.junit.Test;
import chapter1.Question1;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kevin' at '12/29/17 2:29 PM' with Gradle 3.0
 *
 * @author kevin, @date 12/29/17 2:29 PM
 */
public class Question1Test {
    @Test public void testIsUniqueCharsReturnsTrue() {
        assertTrue("isUniqueChars should return 'true' if unique", Question1.isUniqueChars("acbde"));
    }
    @Test public void testIsUniqueCharsReturnsFalse() {
        assertFalse("isUniqueChars should return 'false' if unique", Question1.isUniqueChars("hello"));
    }
}
